#add product
POST http://localhost:3000/api/v1/users/products HTTP/1.1
Content-Type: application/json

{
    "farmer_id":"5f0b7fc96d7acaf714688b2f",
    "productName": "Eggs",
    "quantity":10,
    "productPrice":2 ,
    "productDescription": "excellent product",
    "productImage": ""
}

########signup
POST http://localhost:3000/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
    "firstname":"zereab",
    "lastname":"necha",
    "email":"znecha@mum.edu",
     "password":"1234",
     "role":"farmer",
     "phone_number": "7204515972"
}

###sign in
POST http://localhost:3000/api/v1/users/signin HTTP/1.1
Content-Type: application/json

{
    "email":"lnecha@mum.edu",
    "password":"12345"
  
}

########
#add to cart
PATCH  http://localhost:3000/api/v1/users/5f0b7fc96d7acaf714688b2f/products/5f1e46c68844961f7da43313/cart/1 HTTP/1.1
Content-Type: application/json

###


#add to order and clear cart
PATCH  http://localhost:3000/api/v1/users/5f0b7fc96d7acaf714688b2f/orders HTTP/1.1


###
#get all products by farmer id  (Retrieve products)

GET   http://localhost:3000/api/v1/users/products?farmerId=5f0de3afc610ee2328341e0d HTTP/1.1 
 
###

#get all products by  prod id (Retrieve a product)

GET   http://localhost:3000/api/v1/users/products/5f1612546e5783293e3e002b HTTP/1.1 

###

#delete product
DELETE    http://localhost:3000/api/v1/users//products/?prodId=5f1619753ce8a82d382b5fbd  HTTP/1.1


###

###

#delete all products
DELETE    http://localhost:3000/api/v1/users/products/5f0de3afc610ee2328341e0d HTTP/1.1 


###
###

#update a product
PATCH     http://localhost:3000/api/v1/users/products/?prodId=5f1619f33ce8a82d382b5fbe HTTP/1.1 
Content-Type: application/json

{
    "farmer_id":"5f0de3afc610ee2328341e0d",
    "productName": "potato",
    "productPrice":2 ,
    "productDescription": "Best egg ever",
    "productImage": ""
}
###
#customer get all farmers
GET     http://localhost:3000/api/v1/users/farmers HTTP/1.1 

###


#filter orders by status 
GET      http://localhost:3000/api/v1/users/orders/?pending=pending&ready=ready&complete=complete&farmerId=5f0b7fc96d7acaf714688b2f HTTP/1.1 


###
###


#customer order history
GET      http://localhost:3000/api/v1/users/5f0de392c610ee2328341e0c/orders HTTP/1.1 


###

###


#farmer set order complete 
PATCH       http://localhost:3000/api/v1/users/farmers/5f0e3dc68e0ff65a6bc49b24  HTTP/1.1 
Content-Type: application/json

{
    "order_status":"complete"
}


###

#farmer set order ready and pick up time and send email
PATCH       http://localhost:3000/api/v1/users/farmers/5f0e3f028e0ff65a6bc49b2d  HTTP/1.1 
Content-Type: application/json

{
    "order_status":"ready",
    "pickup_date":"2019-07-15T02:35:56.446Z"


}


###

#get user

GET   http://localhost:3000/api/v1/users/5f0b90022964d7fae42917e0 HTTP/1.1 

###

###
#farmers reputatiion
PATCH   http://localhost:3000/api/v1/users/5f0b7fc96d7acaf714688b2f/reputation/-1
Content-Type: application/json



###
#super user get all users and accounts 
###

GET     http://localhost:3000/api/v1/users/admin



###
#super user patch  passwords
###

PATCH      http://localhost:3000/api/v1/users/5f0b7fc96d7acaf714688b2f/admin
Content-Type: application/json

{
    "password":"12345"
}
###
###
#super user get all transaction orders
###

GET       http://localhost:3000/api/v1/users/orders/transactions?userid=5f0b7fc96d7acaf714688b2f

###