#add product
POST http://localhost:3000/api/v1/users/products HTTP/1.1
Content-Type: application/json

{
    "farmer_id":"5f0ceb2574576174173cbe10",
    "productName": "Cuccumber",
    "quantity":18,
    "productPrice":2 ,
    "productDescription": "excellent product",
    "productImage": ""
}

########signup
POST http://localhost:3000/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
    "firstname":"leul",
    "lastname":"necha",
    "email":"lnecha@mum.edu",
     "password":"1234",
     "role":"customer",
     "phone_number": "7204515972"
}

###sign in
POST http://localhost:3000/api/v1/users/signin HTTP/1.1
Content-Type: application/json

{
    "email":"leul@mum.edu",
    "password":"1234"
  
}

########
#add to cart
PATCH  http://localhost:3000/api/v1/users/5f0ceb2574576174173cbe10 HTTP/1.1
Content-Type: application/json

{
    "prodId":"5f0d2bfdd7fd700701a1ef52",
    "quantity": 7
}
###


#add to order and clear cart
PATCH  http://localhost:3000/api/v1/users/5f0ceb2574576174173cbe10/orders HTTP/1.1


###
#get all products by farmer id (Retrieve products)

GET   http://localhost:3000/api/v1/users/products?farmerId=5f0b90022964d7fae42917e0 HTTP/1.1 

###

#delete product
DELETE    http://localhost:3000/api/v1/users/products/?prodId=5f0ba9376fdf701395d5ad56 HTTP/1.1 


###

###

#delete all products
DELETE    http://localhost:3000/api/v1/users/products/5f0b90022964d7fae42917e0 HTTP/1.1 


###
###

#update a product
PATCH     http://localhost:3000/api/v1/users/products/?prodId=5f0ccaf1220ce75afe63b151 HTTP/1.1 
Content-Type: application/json

{
    "farmer_id":"5f0b90022964d7fae42917e0",
    "productName": "potato",
    "productPrice":2 ,
    "productDescription": "Best egg ever",
    "productImage": ""
}
###
#customer get all farmers
GET     http://localhost:3000/api/v1/users/farmers HTTP/1.1 

###


#filter orders by status 
GET      http://localhost:3000/api/v1/users/orders/?pending=pending&ready=ready&complete=complete HTTP/1.1 


###
###


#customer order history
GET      http://localhost:3000/api/v1/users/orders/?pending=pending&ready=ready&complete=complete HTTP/1.1 


###
